baseurl: http://www.menzenski.com
account: menzenski
github: https://github.com/menzenski
title: Matt Menzenski
subtitle: Slavic Linguistics, Open Access, etc.
#ohrs: 3:00-4:00 TR
#markdown: kramdown

analytics:
  provider: google
  google:
    tracking_id: 'UA-47395716-2'

disqus:           mattmenzenski

#highlighter: pygments


# Owner/author information
owner:
  name:           Matt Menzenski
#  avatar:         avatar.png
  bio:            "PhD student in Slavic Linguistics at the University of Kansas"
  email:          matt.menzenski@gmail.com
  twitter:        menzenski
#  github:         menzenski
#  instagram:      therealmenzenski
#  disqus:         mattmenzenski
  location:       "Lawrence, KS"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, CSS, Jekyll"
  software:       "git"