markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Matt Menzenski
url: http://menzenski.github.io
description: A fantastic blog that is fantastic.
twitter: menzenski

disqus: 'mattmenzenski'
comments: true
