# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true

title: The Programmatic Slavicist
description: The Intersection of Slavic Linguistics and Digital Humanities
author:
  name: Matt Menzenski
  email: menzenski@ku.edu
  github: menzenski
  twitter: 
  pinterest: 
  linkedin: 
  bio: "I'm a graduate student interested in the application of digital humanities methods to Slavic linguistics"
  email_md5: f81b715ebc70f940dee7790071a6a398

analytics :
  provider : google 
  google : 
      tracking_id : 'UA-47395716-1'

comments :
  provider : disqus
  disqus :
    short_name : menzenski

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
asset_path: _assets/images

BASE_PATH: 

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
#
# CNAME (http://yourcustomdomain.com)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://username.github.io)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.io/project-name)
#  A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to "http://username.github.io/project-name"
